[env:waveshare_s3_amoled]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_deps =
    https://github.com/pschatzmann/arduino-audio-driver.git
    https://github.com/pschatzmann/arduino-audio-tools
    https://github.com/pschatzmann/arduino-libhelix
    SD
    SPI
    lewisxhe/SensorLib @ ^0.4.0
    lewisxhe/XPowersLib @ ^0.3.3
    moononournation/GFX Library for Arduino @ ^1.6.5
    adafruit/Adafruit GFX Library @ ^1.12.5
    lewisxhe/FocalTech_Library@^1.0.1

; Hardware-specific overrides
board_build.arduino.memory_type = qio_opi ; Critical for the R8/N16R8 variant
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 32MB ; Some versions report 32MB, but 16MB is safer for partitions
board_build.partitions = default_16MB.csv
monitor_filters = esp32_exception_decoder
build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1